version: "3"

services:

  registry:
    image: descartesresearch/teastore-registry
    ports:
      - "10000:8080"
    environment:
      - SERVICE_PORT=10000
      - HOST_NAME=registry

  db:
    image: descartesresearch/teastore-db
    ports:
      - "13306:3306"

  persistence:
    image: descartesresearch/teastore-persistence
    ports:
      - "1111:8080"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=10000
      - SERVICE_PORT=1111
      - DB_HOST=db
      - DB_PORT=3306

  auth:
    image: descartesresearch/teastore-auth
    ports:
      - "12222:8080"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=10000
      - SERVICE_PORT=12222

  recommender:
    image: descartesresearch/teastore-recommender
    ports:
      - "3333:8080"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=10000
      - SERVICE_PORT=3333

  image:
    image: descartesresearch/teastore-image
    ports:
      - "4444:8080"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=10000
      - SERVICE_PORT=4444

  webui:
    image: descartesresearch/teastore-webui
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=10000
      - SERVICE_PORT=8080